"""
chaotic_pfc
===========
Chaotic communication system based on the Henon map.
"""

from __future__ import annotations

from chaotic_pfc._version import __version__
from chaotic_pfc.analysis.latex_export import (
    export_consolidated_extended_table,
    export_consolidated_full_ranking,
    export_consolidated_top_k_table,
    export_extended_top_k_table,
    export_full_ranking_table,
    export_kaiser_beta_optimal_table,
    export_sweet_spots_table,
    export_top_k_table,
)
from chaotic_pfc.analysis.stats import (
    AreaSummary,
    area_summary,
    best_chaos_preserving,
    beta_curve,
    beta_summary,
    bootstrap_confidence,
    chaos_margin,
    compare_filter_types,
    consolidate_kaiser,
    correlation_matrix,
    export_summary_json,
    kaiser_beta_optimal,
    lmax_distribution,
    lmax_statistics,
    load_all_sweeps,
    optimal_parameters,
    rank_configurations,
    summary_table,
    sweet_spot_per_filter,
    top_k_per_filter,
    transition_boundary,
)
from chaotic_pfc.analysis.sweep import (
    FILTER_TYPES,
    WINDOW_DISPLAY_NAMES,
    WINDOWS,
    SweepResult,
    load_sweep,
    precompute_fir_bank,
    quick_sweep_params,
    run_sweep,
    save_sweep,
)
from chaotic_pfc.analysis.sweep_plotting import (
    classify,
    plot_all,
    plot_chaotic_all,
    plot_chaotic_density,
    plot_chaotic_map,
    plot_classification_interleaved,
    plot_difficulty_map,
    plot_heatmap_continuous,
)
from chaotic_pfc.comms.channel import (
    awgn,
    channel_impulsive,
    channel_multipath,
    fir_channel,
    ideal_channel,
)
from chaotic_pfc.comms.protocols import Channel, Receiver, Transmitter
from chaotic_pfc.comms.receiver import receive, receive_order_n
from chaotic_pfc.comms.transmitter import transmit, transmit_order_n
from chaotic_pfc.dynamics.lyapunov import (
    EnsembleResult,
    LyapunovResult,
    fixed_point_stability,
    lyapunov_henon2d,
    lyapunov_henon2d_ensemble,
    lyapunov_max,
    lyapunov_max_ensemble,
)
from chaotic_pfc.dynamics.maps import (
    henon_filtered,
    henon_fir_sequence,
    henon_generalised,
    henon_order_n,
    henon_standard,
)
from chaotic_pfc.dynamics.signals import binary_message, sinusoidal_message
from chaotic_pfc.dynamics.spectral import psd_normalised

__all__ = [
    "FILTER_TYPES",
    "WINDOWS",
    "WINDOW_DISPLAY_NAMES",
    "AreaSummary",
    "Channel",
    "EnsembleResult",
    "LyapunovResult",
    "Receiver",
    "SweepResult",
    "Transmitter",
    "__version__",
    "area_summary",
    "awgn",
    "best_chaos_preserving",
    "beta_curve",
    "beta_summary",
    "binary_message",
    "bootstrap_confidence",
    "channel_impulsive",
    "channel_multipath",
    "chaos_margin",
    "classify",
    "compare_filter_types",
    "consolidate_kaiser",
    "correlation_matrix",
    "export_consolidated_extended_table",
    "export_consolidated_full_ranking",
    "export_consolidated_top_k_table",
    "export_extended_top_k_table",
    "export_full_ranking_table",
    "export_kaiser_beta_optimal_table",
    "export_summary_json",
    "export_sweet_spots_table",
    "export_top_k_table",
    "fir_channel",
    "fixed_point_stability",
    "henon_filtered",
    "henon_fir_sequence",
    "henon_generalised",
    "henon_order_n",
    "henon_standard",
    "ideal_channel",
    "kaiser_beta_optimal",
    "lmax_distribution",
    "lmax_statistics",
    "load_all_sweeps",
    "load_sweep",
    "lyapunov_henon2d",
    "lyapunov_henon2d_ensemble",
    "lyapunov_max",
    "lyapunov_max_ensemble",
    "optimal_parameters",
    "plot_all",
    "plot_chaotic_all",
    "plot_chaotic_density",
    "plot_chaotic_map",
    "plot_classification_interleaved",
    "plot_difficulty_map",
    "plot_heatmap_continuous",
    "precompute_fir_bank",
    "psd_normalised",
    "quick_sweep_params",
    "rank_configurations",
    "receive",
    "receive_order_n",
    "run_sweep",
    "save_sweep",
    "sinusoidal_message",
    "summary_table",
    "sweet_spot_per_filter",
    "top_k_per_filter",
    "transition_boundary",
    "transmit",
    "transmit_order_n",
]
