# Dependabot configuration
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-deps:
        patterns:
          - "pytest*"
          - "ruff"
          - "mypy"
          - "pre-commit"
        update-types:
          - "minor"
          - "patch"
      docs-deps:
        patterns:
          - "sphinx*"
          - "furo"
          - "sphinx-copybutton"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
