"""Sweep analysis and statistical post-processing."""

from __future__ import annotations

from .latex_export import (
    export_extended_top_k_table,
    export_full_ranking_table,
    export_sweet_spots_table,
    export_top_k_table,
)
from .stats import (
    AreaSummary,
    ConfigRank,
    LmaxStats,
    SweetSpot,
    area_summary,
    best_chaos_preserving,
    beta_curve,
    beta_summary,
    bootstrap_confidence,
    chaos_margin,
    compare_filter_types,
    correlation_matrix,
    export_summary_json,
    lmax_distribution,
    lmax_statistics,
    load_all_sweeps,
    optimal_parameters,
    rank_configurations,
    sweet_spot_per_filter,
    top_k_per_filter,
)
from .sweep import (
    FILTER_TYPES,
    WINDOW_DISPLAY_NAMES,
    WINDOWS,
    SweepResult,
    load_sweep,
    precompute_fir_bank,
    quick_sweep_params,
    run_sweep,
    save_sweep,
)
from .sweep_plotting import (
    classify,
    plot_all,
    plot_chaotic_all,
    plot_chaotic_density,
    plot_chaotic_map,
    plot_classification_interleaved,
    plot_difficulty_map,
    plot_heatmap_continuous,
)

__all__ = [
    "FILTER_TYPES",
    "WINDOWS",
    "WINDOW_DISPLAY_NAMES",
    "AreaSummary",
    "ConfigRank",
    "LmaxStats",
    "SweepResult",
    "SweetSpot",
    "area_summary",
    "best_chaos_preserving",
    "beta_curve",
    "beta_summary",
    "bootstrap_confidence",
    "chaos_margin",
    "classify",
    "compare_filter_types",
    "correlation_matrix",
    "export_extended_top_k_table",
    "export_full_ranking_table",
    "export_summary_json",
    "export_sweet_spots_table",
    "export_top_k_table",
    "lmax_distribution",
    "lmax_statistics",
    "load_all_sweeps",
    "load_sweep",
    "optimal_parameters",
    "plot_all",
    "plot_chaotic_all",
    "plot_chaotic_density",
    "plot_chaotic_map",
    "plot_classification_interleaved",
    "plot_difficulty_map",
    "plot_heatmap_continuous",
    "precompute_fir_bank",
    "quick_sweep_params",
    "rank_configurations",
    "run_sweep",
    "save_sweep",
    "summary_table",
    "sweet_spot_per_filter",
    "top_k_per_filter",
    "transition_boundary",
]
